  version: '3.8'
  services:
    app:
      build: .
      env_file: .env.dev
      ports:
        - "3000:3000"
      depends_on:
        - mongo
    mongo:
      image: mongo:6.0
      restart: unless-stopped
      environment:
        MONGO_INITDB_DATABASE: transcription_db
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db


  volumes:
    mongo-data: